---
resources:
- name: resource-react-tv-epg-codebase
  type: git
  source:
    uri: https://github.com/SatadruBhattacharjee/react-tv-epg.git
    branch: master

jobs:
- name: job-build-react-tv-epg-app
  public: true
  serial: true
  plan:
  - get: resource-react-tv-epg-codebase
    trigger: true
  - task: task-react-tv-epg-app
    file: resource-react-tv-epg-codebase/ci/tasks/task-hello-world.yml
